-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:BOE NV122WUM-N42",
  mode = "1920x1200@60.00",
  position = "-700x-400",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:BOE NV122WUM-N42", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "3", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "4", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "5", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "6", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "7", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "8", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "9", monitor = "desc:BOE NV122WUM-N42" })
hl.workspace_rule({ workspace = "10", monitor = "desc:BOE NV122WUM-N42" })
