-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1",
  mode = "2880x1920@120.00",
  position = "-38x169",
  scale = 1.5,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916",
  mode = "3840x2160@60.00",
  position = "1920x0",
  scale = 1.2,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "3", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "4", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "5", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "6", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "7", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "8", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "9", monitor = "desc:LG Electronics LG ULTRAFINE 204NTEPBE916" })
hl.workspace_rule({ workspace = "10", monitor = "desc:China Star Optoelectronics Technology Co. Ltd MND508ZB1-1", default = true, persistent = true })
