#!/opt/homebrew/bin/fish

function fancy_echo
    printf "\n$argv\n"
end

# Install, update or delete fisher packages
fancy_echo 'Installing, updating and cleaning fisher packages ...'
fish -c "fisher update"

# Install, update and clean Tmux Plugin Manager plugins
$HOME/.tmux/plugins/tpm/bin/install_plugins
$HOME/.tmux/plugins/tpm/bin/clean_plugins
$HOME/.tmux/plugins/tpm/bin/update_plugins all

# Set Fish color palette
fish_config theme choose "Catppuccin Macchiato"

# Execute the function to clean symlinks
fancy_echo 'Clean symlinks'
clean_symlinks

# Reload fish
reload
