#!/opt/homebrew/bin/fish

function fancy_echo
    printf "\n$argv\n"
end

# Install or update fisher
if not functions -q fisher
    fancy_echo 'Installing fisher ...'
    set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
    curl https://git.io/fisher --create-dirs -sLo $XDG_CONFIG_HOME/fish/functions/fisher.fish
end

# Install or update themes

# Create configuration directories
mkdir -p ~/.config/fish/themes
mkdir -p ~/.config/delta/themes
mkdir -p "$(bat --config-dir)/themes"

# Fish
wget -P ~/.config/fish/themes https://github.com/catppuccin/fish/raw/main/themes/Catppuccin%20Frappe.theme
wget -P ~/.config/fish/themes https://github.com/catppuccin/fish/raw/main/themes/Catppuccin%20Latte.theme
wget -P ~/.config/fish/themes https://github.com/catppuccin/fish/raw/main/themes/Catppuccin%20Macchiato.theme
wget -P ~/.config/fish/themes https://github.com/catppuccin/fish/raw/main/themes/Catppuccin%20Mocha.theme

# Delta
wget -P ~/.config/delta/themes https://github.com/catppuccin/delta/raw/main/catppuccin.gitconfig

# Bat
wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Latte.tmTheme
wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Frappe.tmTheme
wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Macchiato.tmTheme
wget -P "$(bat --config-dir)/themes" https://github.com/catppuccin/bat/raw/main/themes/Catppuccin%20Mocha.tmTheme

# Build bat cache
bat cache --build

fancy_echo "Themes updated!"
