#!/opt/homebrew/bin/fish

function fancy_echo
    printf "\n$argv\n"
end

# Install or update fisher
if not functions -q fisher
    fancy_echo 'Installing fisher ...'
    set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
    curl https://git.io/fisher --create-dirs -sLo $XDG_CONFIG_HOME/fish/functions/fisher.fish
end

# Install Tmux Plugin Manager
if [ ! -d "$HOME/.tmux/plugins/tpm" ]
    fancy_echo "Installing Tmux Plugin Manager ..."
    git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
end

# Install or update themes
update_themes
