[bar.default]
background_opacity = 0.84999999999999998
center = [ "taskbar" ]
end = [ "group:g2", "group:g3", "volume", "battery", "group:g1", "session" ]
margin_edge = 0
margin_ends = 0
radius = 0
shadow = false
start = [ "control-center", "clock", "weather", "tray", "active_window", "privacy" ]
thickness = 40
widget_spacing = 14

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g2"
    members = [ "network_rx", "network_tx", "cpu", "ram" ]
    opacity = 0.0
    padding = 0.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g3"
    members = [ "network", "bluetooth" ]
    opacity = 0.0
    padding = 20.0

    [[bar.default.capsule_group]]
    fill = "surface_variant"
    id = "g1"
    members = [ "screenshot", "recorder", "wallpaper", "caffeine", "notifications" ]
    opacity = 0.0
    padding = 20.0

[calendar]
enabled = true

    [calendar.account.nebulab]
    name = "Nebulab"
    type = "google"

    [calendar.account.nebulab_google]
    name = "Nebulab"
    type = "google"

[desktop_widgets]
enabled = false

[dock]
auto_hide = true
enabled = false
icon_size = 36
reserve_space = false

[idle]
behavior_order = [ "Reduce Brightness", "Keyboard Brightness", "lock", "screen-off", "lock-and-suspend" ]
pre_action_fade_seconds = 0

    [idle.behavior."Keyboard Brightness"]
    action = "command"
    command = "kbd_backlight 0"
    enabled = true
    timeout = 180.0

    [idle.behavior."Reduce Brightness"]
    action = "command"
    command = "brightnessctl -s set 10"
    enabled = true
    resume_command = "brightnessctl -r"
    timeout = 180.0

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 400.0

[location]
address = ""
auto_locate = true

[lockscreen]
blurred_desktop = true
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@DP-4", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-4"]
    box_height = 70.0
    box_width = 400.0
    cx = 1600.0
    cy = 1681.0
    output = "DP-4"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-4".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 960.0
    cy = 1081.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[nightlight]
enabled = true

[osd.kinds]
bluetooth = false
keyboard_layout = false
media = false
wifi = true

[plugin_settings."noctalia/screen_recorder"]
color_range = "full"
copy_to_clipboard = true

[plugins]
enabled = [ "noctalia/screen_recorder" ]

[shell]
clipboard_enabled = true
font_family = "GeistMono NF"
launch_apps_as_systemd_services = true
polkit_agent = true
settings_show_advanced = true

    [shell.panel]
    session_placement = "centered"
    wallpaper_placement = "floating"

    [shell.screenshot]
    copy_to_clipboard = false
    directory = "~/Pictures/Screenshots"
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    shortcut = "l"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    shortcut = "o"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    enabled = true
    shortcut = "u"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    command = "hyprshutdown -t 'Restarting...' --post-cmd 'reboot'"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    command = "hyprshutdown -t 'Shutting down...' --post-cmd 'shutdown -P 0'"
    enabled = true
    shortcut = "s"
    variant = "destructive"

    [shell.shadow]
    alpha = 0.19999999552965164

[theme]
builtin = "Catppuccin"
community_palette = "ADW"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "hyprland", "qt", "wezterm" ]
    community_ids = [ "vicinae", "telegram", "yazi" ]
    enable_builtin_templates = true
    enable_community_templates = true

[wallpaper]
directory = "~/Pictures/Wallpapers"

    [wallpaper.automation]
    enabled = true

    [wallpaper.default]
    path = "/home/alessio/Pictures/Wallpapers/nebulab.jpg"

    [wallpaper.last]
    path = "/home/alessio/Pictures/Wallpapers/nebulab.jpg"

    [wallpaper.monitors.DP-4]
    path = "/home/alessio/Pictures/Wallpapers/nebulab.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/alessio/Pictures/Wallpapers/nebulab.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "/home/alessio/Pictures/Wallpapers/nebulab.jpg"
    theme_mode = "dark"

[widget.active_window]
max_length = 180
title_scroll = "on_hover"

[widget.battery]
display_mode = "graphic"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.clock]
format = "%a %e %b %H:%M"

[widget.cpu]
show_label = false

[widget.media]
hide_when_no_media = true
max_length = 180
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.network_rx]
show_label = false

[widget.network_tx]
show_label = false

[widget.privacy]
capsule = true
capsule_opacity = 0.0
capsule_padding = 20.0
hide_inactive = true

[widget.ram]
show_label = false
stat = "ram_pct"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.taskbar]
group_by_workspace = true
group_single_icon_per_app = true
hide_empty_workspaces = true
workspace_label_placement = "inside"

[widget.tray]
capsule = true
capsule_opacity = 0.0
capsule_padding = 20.0
drawer = true

[widget.weather]
show_condition = false

[widget.workspaces]
active_pill_size = 2.0
display = "name"
empty_color = "primary"
focused_color = "tertiary"
hide_when_empty = true
occupied_color = "primary"
